// <auto-generated />
namespace PrivacyManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetables));
        
        string IMigrationMetadata.Id
        {
            get { return "202204010904583_updatetables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
